Fr o fetch price la
meiyiniu/electricitymaps-contrib pull request #2
Opened 2022-12-11 23:07 UTC by meiyiniu

Co-authored-by: Julia Du <julia_du@outlook.com>

## Issue

[#4747](https://github.com/electricitymaps/electricitymaps-contrib/issues/4747)

## Description

Fetches prices for the `FR_O` zones, which are available only for historical data. The price is no longer reported since the beginning of 2020, but historical data can still be meaningful to know.

2022-12-14 01:19 UTC, cynding requested changes
Overall, lgtm! I like the added unit test. Nice job :)

Requested a small change.

2022-12-14 01:19 UTC, cynding commented on parsers/FR_O.py
> +    if target_datetime is None:
I see that we call ```fetch_data``` just below, and ```fetch_data``` will perform this exact predicate check, so we don't need this check duplicated here, since it will be thrown by ```fetch_data```. 

Let's remove it.

2022-12-14 01:56 UTC, meiyiniu commented on parsers/FR_O.py
> +    if target_datetime is None:
Fixed in [a50f116](https://github.com/meiyiniu/electricitymaps-contrib/pull/2/commits/a50f116f596e9afd83b019c4ca684620a0dbf1e2) - please give it a re-review!

2022-12-14 01:58 UTC, cynding approved these changes

2022-12-15 03:56 UTC, nathantau approved these changes
LGTM 👍

2022-12-15 23:29 UTC, merged